### PR TITLE
docs: document missed server variable in the example

### PR DESCRIPTION
**Pull request by magicmatatjahu**
Reading the old issues, I checked that https://github.com/asyncapi/spec/issues/371 issue is still unresolved, so this PR fixes it.

Changes:
- document missed server variable (`{basePath}`) in the example.

Related issue(s)
Resolves https://github.com/asyncapi/spec/issues/371

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@derberg As I know you are preparing the release process, so probably my case is important for you. I only updated the example in the spec, not any description/sentences in spec, but only single example, so I think that it should be merged without release of the `2.1.1` spec.

**Comment by derberg** [comment]
@magicmatatjahu My statement would be that examples are not part of the spec, so even though they are in `asyncapi.md` file, we should not release `2.1.1` because of example fix. We should only do patch releases when there are changes to the main content, the specification itself, the text that describes it.

The only issue with this approach is that this means we will merge this PR without release and it will not be reflected on the AsyncAPI Website, so we need to enhance a release pipeline here to cover such cases.

I wonder what others think

**Comment by magicmatatjahu** [comment]
@derberg I think that we can use the `on.push.paths` https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths to run https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml on every release and push

**Comment by magicmatatjahu** [comment]
I added PR for updating spec on website - https://github.com/asyncapi/spec/pull/591

**Pull request merged**
