### PR TITLE
docs: operation trait object description

### PR DESCRIPTION
**Pull request by akkshitgupta**
---
title: "FIX: operation trait object description"
---

---

## **Related issue(s):** fixes: #994

| Earlier                                                                                                                                   | Now                                                                                               |
| ----------------------------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------ |
| the description didn't exclude the `messages` field as `operation trait object` doesn't have `messages` field like `action` or `channel`. | the exclusion list includes the `messages` field as well along with others.                       |
| Earlier                                         | Updated |

Add the ✏️ Editorial label.

NOTE: I found a number of MarkDown linting errors. Just want to confirm is it fine to Push the refactored changes in the same Pull Request or open a New Pull Request.

> Always make sure that the specification markdown file has no markdown-related errors.

### CODE REVIEW

**Comment by akkshitgupta** [comment]
hey @akshatnema @smoya it would be great id you review the pull request for any changes or anything

**Comment by smoya** [comment]
> NOTE: I found a number of MarkDown linting errors. Just want to confirm is it fine to Push the refactored changes in the same Pull Request or open a New Pull Request.

I would recommend you do it better in a new PR

**Comment by akkshitgupta** [comment]
sure @smoya I will raise a new PR by improving the MarkDown linting as per the standards once this gets merged to avoid any conflicts

**Comment by smoya** [comment]
@akshatnema please change the title prefix to `docs:` so we do not release a new fix but rather we consider this as an ambiguity in docs. The JSON Schema docs are not changing either.

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Review by derberg — APPROVED** [review]
LGTM

I will every PR has such a good and clear description, showing state before and after applying PR. Such a speed up for maintainer to do a review ❤️

**Pull request merged**
