### PR TITLE
feat: add Anypoint MQ protocol to list of supported bindings

### PR DESCRIPTION
**Pull request by GeraldLoeffler**
---
title: "Create Anypoint MQ protocol"
---

Added protocol `anypointmq` to the spec.
A separate PR will be submitted against the bindings repo https://github.com/asyncapi/bindings for the corresponding bindings definitions.

---

**Related issue(s):**
#514 

---

### CODE REVIEW

**Review by fmvilas — COMMENTED** [review]
Looks good to me. I'm just missing the protocol bindings in the github.com/asyncapi/bindings repo.

**Comment by GeraldLoeffler** [comment]
> Looks good to me. I'm just missing the protocol bindings in the github.com/asyncapi/bindings repo.

@fmvilas : i've now pushed the matching PR against the bindings repo: https://github.com/asyncapi/bindings/pull/63

**Comment by derberg** [comment]
@GeraldLoeffler lgtm but please change base branch from `master` to `2021-09-release`

**Comment by GeraldLoeffler** [comment]
okay @derberg , i've managed to change the base branch of this PR from `master` to `2021-09-release` (and successfully battled the file change complication this caused): done

**Review by derberg — APPROVED** [review]
LGTM, we just need to first merge https://github.com/asyncapi/spec-json-schemas/pull/90, then I will help with PR to the parser and can move this proposal to stage 3 and merge 🥳 

@fmvilas anything from your side?

**Review by fmvilas — APPROVED** [review]
Ship it!

**Pull request merged**
