### PR TITLE
chore: remove `a` tags from spec headings

### PR DESCRIPTION
**Pull request by aayushmau5**
title: "Remove all the `a` tags from headings"
---

### CODE REVIEW

**Comment by aayushmau5** [comment]
:thinking:  The `lint` action is failing because of the missing `a` tags?

**Comment by magicmatatjahu** [comment]
@aayushmau5 Instead of removing tags from spec, you can delete them in the https://github.com/asyncapi/website/blob/master/components/navigation/DocsNavItem.js when page is rendered.

**Comment by aayushmau5** [comment]
oh, never really thought about that. I'm going to try that approach.

**Comment by aayushmau5** [comment]
Will be closing this PR in favor of https://github.com/asyncapi/website/pull/283

**Pull request closed without merging**
