### PR TITLE
docs: fix URN examples

### PR DESCRIPTION
**Pull request by mike-schenk**
---
title: "Use valid URIs or URNs in Identifier examples"
---

Changes invalid URN examples to either valid URIs or to valid URNs according to the linked RFC 8141 and its associated IANA URN namespaces registry.

Reverse DNS names do not form valid URNs. The registry of defined [URN namespace identifiers](https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml) is quite limited. Because of that, it seems unlikely that a valid URN will actually be useful in the context of an AsyncAPI document, but to make the minimal change in the spec document, I used the `example` namespace identifier.

Instead of a URN, a URI with the registered [`tag` scheme](https://www.rfc-editor.org/rfc/rfc4151.html) seems to apply better. Since the semantics of the tag URI scheme appear to match the desired intent of a universally-unique and long-lived identifier.

This is an editorial change, but I apparently can't set that label myself.

---

**Related issue(s):**

---

### CODE REVIEW

**Comment by derberg** [comment]
@mike-schenk hi, I'm really sorry for getting so late here. Can you solve merge conflicts please 🙏🏼 

@fmvilas @dalelane anything from your side?

**Review by fmvilas — APPROVED** [review]
Looks good to me 👍

**Review by dalelane — APPROVED** [review]
looks good

@mike-schenk - would you like some help with the merge conflicts?

**Comment by mike-schenk** [comment]
Merge conflicts resolved.

**Review by dalelane — APPROVED** [review]
👍

**Comment by fmvilas** [comment]
Forget about the last comment saying it was released in version 2.5.0-next-major-spec.1. I made a mistake and it created this version but it should actually be `3.0.0-next-major-spec.1`. There's a notice in the [release](https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-major-spec.1). Apologies for the noise.

**Comment by derberg** [comment]
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899

**Pull request merged**
