### PR TITLE
Solving issue number #1080

### PR DESCRIPTION
**Pull request by maskedwolf4**
Solving issue #1080 
---
 "The official website's command to try is not even working in the first place"
---
---
The terminal was showing the msg on running cmd from website like:
npm warn deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated read-package-json@5.0.2: This package is no longer supported. Please use @npmcli/package-json instead.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated domexception@2.0.1: Use your platform's native DOMException instead
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated rimraf@2.2.8: Rimraf versions prior to v4 are no longer supported
npm warn deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm warn deprecated @asyncapi/generator-hooks@0.1.0: Hooks are now part of generator repository and also out of the box integrated with the generator, so no need to set it as dependency any more: https://github.com/asyncapi/generator/releases/tag/%40asyncapi%2Fgenerator%402.5.0
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm warn deprecated @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated @hyperjump/json-schema-core@0.28.5: This package was rolled into @hyperjump/json-schema as of v1.0.0
---

---

*Code Changes Done*
-Added install.sh script to remove deprecating messages
-Modified run command in validate-examples.yml giving cmd to run install.sh
-The terminal will show msg "Async API installed successfully"

---

### CODE REVIEW

**Comment by smoya** [comment]
@maskedwolf4 would you mind sharing what are you really trying to achieve here? Hidding warnings? What is the reason about?

**Comment by maskedwolf4** [comment]
Actually it's my first contribution I'm not that much experienced and was bit confused 
Could you help me with it??

**Comment by maskedwolf4** [comment]
> @maskedwolf4 would you mind sharing what are you really trying to achieve here? Hidding warnings? What is the reason about? 

When I used the npm install it showed me all the warnings of deprecated versions. So better show msg of showing installation completed rather than showing such output 

And also I have some installation problems

**Comment by smoya** [comment]
> > @maskedwolf4 would you mind sharing what are you really trying to achieve here? Hidding warnings? What is the reason about? 
> 
> When I used the npm install it showed me all the warnings of deprecated versions. So better show msg of showing installation completed rather than showing such output 
> 
> And also I have some installation problems 
> 

Warnings should be always there; we should rather work on fixing those warnings (updating deprecated packages for example) rather than hiding them. Hiding them seems like sweeping under the rug.

Would you mind sharing what are the exact commands you are following, a link to the exact asyncapi website page they are shown, and the issues you are facing?

**Comment by maskedwolf4** [comment]
> > > @maskedwolf4 would you mind sharing what are you really trying to achieve here? Hidding warnings? What is the reason about?
> > 
> > 
> > When I used the npm install it showed me all the warnings of deprecated versions. So better show msg of showing installation completed rather than showing such output
> > And also I have some installation problems
> 
> Warnings should be always there; we should rather work on fixing those warnings (updating deprecated packages for example) rather than hiding them. Hiding them seems like sweeping under the rug.
> 
> Would you mind sharing what are the exact commands you are following, a link to the exact asyncapi website page they are shown, and the issues you are facing?

Screenshot 2024-12-26 232239

I have shared the SS of the commands and problems I'm facing. The commands I used are:
 **npm install -g @asyncapi/cli
asyncapi generate fromTemplate https://bit.ly/asyncapi @asyncapi/html-template -o example**

Can you suggest what should I do to solve this bug and essential tips to contribute so that I don't do such mistakes again

**Comment by smoya** [comment]
> > > > @maskedwolf4 would you mind sharing what are you really trying to achieve here? Hidding warnings? What is the reason about?
> > > 
> > > 
> > > When I used the npm install it showed me all the warnings of deprecated versions. So better show msg of showing installation completed rather than showing such output
> > > And also I have some installation problems
> > 
> > Warnings should be always there; we should rather work on fixing those warnings (updating deprecated packages for example) rather than hiding them. Hiding them seems like sweeping under the rug.
> > 
> > Would you mind sharing what are the exact commands you are following, a link to the exact asyncapi website page they are shown, and the issues you are facing?
> 
> Screenshot 2024-12-26 232239
> 
> I have shared the SS of the commands and problems I'm facing. The commands I used are:
>  **npm install -g @asyncapi/cli
> asyncapi generate fromTemplate https://bit.ly/asyncapi @asyncapi/html-template -o example**
> 
> Can you suggest what should I do to solve this bug and essential tips to contribute so that I don't do such mistakes again
> 

I can't see any bug happening in that execution. The error says the operation got aborted. Aren't you aborting the operation manually?

**Comment by maskedwolf4** [comment]
Actually it's my first contribution I'm not that much experienced and was bit confused 
Could you help me with it??

**No**

**Comment by derberg** [comment]
This PR is not addressing https://github.com/asyncapi/spec/issues/1080

The problem is website-related.

@maskedwolf4 if you really wanna help open source maintainers, you need first to read the contribution guide, understand requirements, and never start with PR in a project you are unfamiliar with. Always clarify first the issue, what the problem is, and how it can be fixed. To be honest, open source or regular job on closed source - first, always clarify the scope of the work, and then do the work. The linked issue is transferred to `website` repo now. If you are still interested, please follow my instructions and continue in the issue.

✌🏼

**Comment by maskedwolf4** [comment]
> This PR is not addressing [asyncapi/website#3522](https://github.com/asyncapi/website/issues/3522)
> 
> The problem is website-related.
> 
> @maskedwolf4 if you really wanna help open source maintainers, you need first to read the contribution guide, understand requirements, and never start with PR in a project you are unfamiliar with. Always clarify first the issue, what the problem is, and how it can be fixed. To be honest, open source or regular job on closed source - first, always clarify the scope of the work, and then do the work. The linked issue is transferred to `website` repo now. If you are still interested, please follow my instructions and continue in the issue.
> 
> ✌🏼

Sure

**Comment by derberg** [comment]
see you in https://github.com/asyncapi/website/issues/3522

**Pull request closed without merging**
