### PR TITLE
docs: fix version in asyncapi.md

### PR DESCRIPTION
**Pull request by xunto**
## title: "fix version in asyncapi.md`"
Noticed wrong version on website when I was reading through AsyncAPI Specification.

### CODE REVIEW

**Review by derberg — APPROVED** [review]
oh, good eye, thanks!

**Review by fmvilas — APPROVED** [review]

**Comment by aaronkorver** [comment]
Note, there are more references than that, see PR #704

**Comment by derberg** [comment]
https://github.com/all-contributors please add @xunto for doc

**Comment by derberg** [comment]
@all-contributors please add @xunto for doc

**Pull request merged**
