### PR TITLE
chore(ci): change pages to markdown

### PR DESCRIPTION
**Pull request by Shurtu-gal**
See https://github.com/asyncapi/website/pull/2938

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]

**Comment by Shurtu-gal** [comment]
@akshatnema could you remove the `do-not-merge` label.

**Comment by akshatnema** [comment]
I wish I could, but I don't have maintainer access here 😅. 

@fmvilas @derberg Can you please help 🙏

**Pull request merged**
