### PR TITLE
docs: align text definition of Message.payload with it's field definition

### PR DESCRIPTION
**Pull request by char0n**
---
title: "Align text definition of Message.payload with it's field definition"
---

> NOTE: this is an editorial change

---

**Related issue(s):**

- #928

---

### CODE REVIEW

**Review by derberg — APPROVED** [review]
lgtm

**Review by smoya — APPROVED** [review]
LGTM

**Review by dalelane — APPROVED** [review]

**Comment by char0n** [comment]
@fmvilas just pinging here

**Pull request merged**
