### PR TITLE
chore: set 2.5.0 as the latest version of the spec

### PR DESCRIPTION
**Pull request by smoya**
This PR sets all references from `2.4.0` to `2.5.0`, including examples.

### CODE REVIEW

**Comment by fmvilas** [comment]
What are all these changes? Did you create the branch from master maybe?

**Comment by smoya** [comment]
> What are all these changes? Did you create the branch from master maybe?

Yes, as the `next-spec` branch was completely out of date.

**Comment by smoya** [comment]
> can we have update of branch separate, and then 2.5 changes?

done. https://github.com/asyncapi/spec/pull/810

**Comment by smoya** [comment]
@derberg @fmvilas @dalelane this is ready to be reviewed

**Review by derberg — COMMENTED** [review]
one small fix needed

**Review by derberg — APPROVED** [review]

**Pull request merged**
