### PR TITLE
chore: update release branch to 3.0 

### PR DESCRIPTION
**Pull request by jonaslagoni**
Todo:

- [x] Retarget branch to new release branch

**Related issues**
Blocked by https://github.com/asyncapi/spec/pull/758

### CODE REVIEW

**Comment by derberg** [comment]
@jonaslagoni please also update Readme

**Comment by jonaslagoni** [comment]
Sorry for all the commits, created this branch from master, those changes were addressed in https://github.com/asyncapi/spec/pull/758 :) I am too lazy to create another branch and rebase it with the changes, as it has no benefit 🤷

**Comment by jonaslagoni** [comment]
> @jonaslagoni please also update Readme

Done 👍

**Review by derberg — APPROVED** [review]

**Comment by jonaslagoni** [comment]
Thanks @derberg 🎉 

/rtm

**Pull request merged**
