### PR TITLE
docs: update readme, add sponsors section, review requested

### PR DESCRIPTION
**Pull request by AnimeshKumar923**
---
title: "sponsors section add in README.md"
---
closes issue #883 
---

**Related issue(s):**
bump.sh logo not clearly visible, help required @derberg 
---

### CODE REVIEW

**Comment by AnimeshKumar923** [comment]
@derberg bump logo not clearly visible, help is required

**Comment by sambhavgupta0705** [comment]
you can also share a preview image of this if its possible

**Comment by AnimeshKumar923** [comment]
> you can also share a preview image of this if its possible

Okay, sharing it in few moments...

**Comment by AnimeshKumar923** [comment]
> you can also share a preview image of this if its possible

Here it is:

sponsors-section-preview

**Comment by derberg** [comment]
yeah, the dark mode 😞 I think there is some solution, but don't remember what it requires. Looks like officially recommended way is https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/25423296/163456776-7f95b81a-f1ed-45f7-b7ab-8fa810d529fa.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
  <img alt="Shows an illustrated sun in light mode and a moon with stars in dark mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

in light mode it is ok

Screenshot 2022-12-15 at 10 11 14

Just please remove logos of sponsors from top of the readme

**Comment by AnimeshKumar923** [comment]
> just a suggestion that we can bump.sh logo on white background just as redhat logo ,that will work fine in dark mode also
> @AnimeshKumar923 

I will try that and update about it.

**Comment by AnimeshKumar923** [comment]
@derberg please review the changes

**Review by fmvilas — APPROVED** [review]

**Comment by AnimeshKumar923** [comment]
Feels good when the PR you're working on gets merged. Thank you @derberg

**Comment by derberg** [comment]
thanks @AnimeshKumar923 for contributing the change 🙇‍♂️

**Comment by AnimeshKumar923** [comment]
> thanks @AnimeshKumar923 for contributing the change 🙇‍♂️ 

@derberg it's my pleasure sir, I'm new to open source so looking forward to more contributions.🙇🚀

**Comment by derberg** [comment]
Congrats on getting your stuff merged at AsyncAPI.
Feel free to join our Slack https://asyncapi.com/slack-invite 

we also list good first issues in this dashboard -> https://www.asyncapi.com/community/dashboard

**Comment by smoya** [comment]
@all-contributors please add @AnimeshKumar923  for content,doc,maintenance

**Pull request merged**
