### PR TITLE
docs: fix websocket-gemini message's payload example

### PR DESCRIPTION
**Pull request by magicmatatjahu**
---
title: "fix: websocket-gemini message's payload example"
---

---

**Related issue(s):**
https://github.com/asyncapi/studio/issues/526

---

Fix the payload example in one of the messages of the `websocket-gemini` example.

### CODE REVIEW

**Review by derberg — APPROVED** [review]
good catch, thanks!

**Review by fmvilas — APPROVED** [review]

**Review by char0n — APPROVED** [review]
LGTM :+1:

**Pull request merged**
