### PR TITLE
docs: add example for websocket with bindings

### PR DESCRIPTION
**Pull request by derberg**
adding a missing websocket example that many people ask for

preview here: https://playground.asyncapi.io/?url=https://raw.githubusercontent.com/derberg/asyncapi/add-websocket-example/examples/2.0.0/websocket-gemini.yml

### CODE REVIEW

**Review by fmvilas — DISMISSED** [review]
🚀 💯

**Comment by derberg** [comment]
@fmvilas please approve again. I fixed server name I noticed during my life stream, left over from my asyncapi file about Shrek app :)

**Review by fmvilas — APPROVED** [review]

**Comment by derberg** [comment]
It is actually not included in the release. This was an unintentional release caused by the release automation initial run. 1.0 version of the spec was released a long time ago. The release mentioned by the bot was removed.

**Comment by derberg** [comment]
Not included in release 2.1 yet, 2.1 was mistakenly triggered by our automation.

**Pull request merged**
