### PR TITLE
docs: end OAuth Flows Object field descriptions always with dot

### PR DESCRIPTION
**Pull request by char0n**
Some fixed fields description have dots and some don't. This PR provides remediation and introduces a little bit more consistency.

### CODE REVIEW

**Review by smoya — CHANGES_REQUESTED** [review]
LGTM, however I think `docs:` commit prefix fits better than `refactor:`.

**Comment by char0n** [comment]
> LGTM, however I think `docs:` commit prefix fits better than `refactor:`.

Sure, can be address by `squash and merge` workflow, or do you want me to force push a new amended commit msg?

**Comment by smoya** [comment]
> > LGTM, however I think `docs:` commit prefix fits better than `refactor:`.
> 
> Sure, can be address by `squash and merge` workflow, or do you want me to force push a new amended commit msg?

You just need to change it in the PR title. The PR title is used as the commit message when squashing.

**Comment by char0n** [comment]
Done.

**Review by fmvilas — DISMISSED** [review]
Looks good to me too.

@derberg is our CI aware of things like `docs(asyncapi.md):` in the PR title? Or should we just use `docs:` or `chore:`?

**Comment by derberg** [comment]
@char0n no worries, happy to explain.

The only difference is that if you make an editorial change against `next-major`, then the change will wait until the next release window to get released. And if the change is introduced against `master`, and with `docs:` prefix, then we update it also automatically on asyncapi.com

so yeah, `editorial changes` is a key here, because if it is more, then yeah, should not go to `master`

**Comment by fmvilas** [comment]
Forget about the last comment saying it was released in version 2.5.0-next-major-spec.1. I made a mistake and it created this version but it should actually be `3.0.0-next-major-spec.1`. There's a notice in the [release](https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-major-spec.1). Apologies for the noise.

**Comment by derberg** [comment]
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899

**Pull request merged**
