### PR TITLE
docs: clarify the resolution rules of Channel Item `$ref` field

### PR DESCRIPTION
**Pull request by char0n**
Refs #612

### CODE REVIEW

**Comment by fmvilas** [comment]
I think this PR can be removed in favor of #777?

**Comment by char0n** [comment]
@fmvilas this change is for 2.x branch, the #777 is for 3.x branch. Assuming we don't know exactly how soon the 2.x branch of the spec goes away and it will clarify for 2.x consumers what the resolutions rules are.

**Comment by derberg** [comment]
is it really needed? taking into account that the field is anyway deprecated, which means "do not use it"

**Comment by char0n** [comment]
@derberg it's up to you to decide. I can only provide reasons why it would be maybe appropriate:

The only reason I created the PR is that I work on tooling implementation and I needed to implement resolution mechanism for this. I made an assumption that resolution here adheres to JSON Reference spec. This was not clear from the specification for me. Even though we say "do not use it" the mechanism is there and it should be crystal clear how it works, even though it's deprecated.

This doesn't change the specification in any way, it just clarifies something that is currently up to implement-or interpretation.

**Review by fmvilas — APPROVED** [review]
Looks good to me 👍

**Comment by char0n** [comment]
@derberg @dalelane can I ask you to look into this PR? Thanks!

**Review by dalelane — APPROVED** [review]

**Review by derberg — APPROVED** [review]
sorry for keeping you waiting 😞 

this one doesn't have to wait for 2.5 as this is an editorial change that points to `master`

/rtm

**Comment by fmvilas** [comment]
Forget about the last comment saying it was released in version 2.5.0-next-major-spec.1. I made a mistake and it created this version but it should actually be `3.0.0-next-major-spec.1`. There's a notice in the [release](https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-major-spec.1). Apologies for the noise.

**Comment by derberg** [comment]
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899

**Pull request merged**
