### PR TITLE
feat!: release for version 3.0.0 of the spec

### PR DESCRIPTION
**Pull request by jonaslagoni**
This PR is created upfront to reflect on a daily basis what things are included in the release.

Also, the reason to create this PR a long time before the release is to enable automation (bot keeps upstream branches always up to date with master, see this [action](https://github.com/asyncapi/spec/blob/master/.github/workflows/autoupdate.yml)) that we have in place to regularly update the release branch with whatever is changed in the master branch. So nobody has to do it manually.

#### TO DO:

* [ ] Cherry-pick #753 commit right before merging this PR. There's a backup branch where you'll be able to find this commit: https://github.com/asyncapi/spec/tree/next-major-spec-backup.

### CODE REVIEW

**Comment by fmvilas** [comment]
I wonder why this PR is having conflicts. I was looking at the changes in #807 and they all seem pretty straightforward to auto-merge for git but for some reason, it's not doing it.

**Comment by fmvilas** [comment]
> as there are no changes in this branch either

There are changes. In this branch, for instance, the examples are already "migrated" to version 3.0.0 and the spec already has the version number updated too. Still not enough to get this amount of conflicts IMO but worth mentioning.

**Comment by derberg** [comment]
@jonaslagoni fyi there are many merge conflicts, because of this bot is not able to keep it up to date with `master`

**Comment by fmvilas** [comment]
Let me have a look. I'm gonna rebase and cherry-pick to try to clean the history. Let's see if it works.

**Comment by fmvilas** [comment]
Alright, so I think I found the problem (or at least the PR that's causing the majority of them). #753 is changing a lot of files replacing `2.3.0` with `3.0.0`. We do this on every minor release too so it's going to conflict every time we have a new release until we get 3.0.0. My suggestion is that we leave #753 out and we reapply it again when the time to release 3.0.0 arrives. Is everyone ok with this?

**Review by derberg — APPROVED** [review]

**Comment by smoya** [comment]
Because of [this issue](https://github.com/asyncapi/.github/issues/263), we need to manually merge this PR if we want to keep mentions to the co-authors of this PR. 

So please, when merging, add the following commit message description literally (with the two empty lines at the beginning as well):

```


Co-authored-by: Sergio Moya <1083296+smoya@users.noreply.github.com>
Co-authored-by: nickshoe <32668766+nickshoe@users.noreply.github.com>
Co-authored-by: Rishi <52498617+kaushik-rishi@users.noreply.github.com>
Co-authored-by: asyncapi-bot-eve <bot+eve@asyncapi.io>
Co-authored-by: Fran Méndez <fmvilas@gmail.com>
Co-authored-by: Heiko Henning <greenrover33@gmail.com>
Co-authored-by: Lukasz Gornicki <lpgornicki@gmail.com>
Co-authored-by: samz <samir.amzani@gmail.com>
Co-authored-by: Maciej Urbańczyk <urbanczyk.maciej.95@gmail.com>
Co-authored-by: Vladimír Gorej <vladimir.gorej@gmail.com>
```

**Review by smoya — APPROVED** [review]

**Pull request merged**
