### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PrakharSachan5342**
Removing Platinum sponsors section as it is outdated and we maintain up to date list in most popular repo -> https://github.com/asyncapi/spec

Have successfully removed platinum sponsors 

If you want any other changes i could help doing it

### CODE REVIEW

**Comment by char0n** [comment]
@derberg is this something that we want to do?

**Comment by PrakharSachan5342** [comment]
> @derberg is this something that we want to do?

yes @derberg told to remove the platinum sponsors list as it is out dated , pls accept my pr

**Comment by dalelane** [comment]
@PrakharSachan5342 I think perhaps you misunderstood [the comment](https://github.com/asyncapi/community/issues/927#issuecomment-1799255383)

The suggestion was to remove the platinum sponsors section from https://github.com/asyncapi/community/blob/master/README.md because there was an up to date version in this repo's README. The suggestion was not to remove the up to date version in this repo's README.

**Comment by derberg** [comment]
> @PrakharSachan5342 I think perhaps you misunderstood https://github.com/asyncapi/community/issues/927#issuecomment-1799255383
The suggestion was to remove the platinum sponsors section from https://github.com/asyncapi/community/blob/master/README.md because there was an up to date version in this repo's README. The suggestion was not to remove the up to date version in this repo's README.

💯 what @dalelane wrote
@PrakharSachan5342 you opened a PR in a wrong repo. Here we maintain up to date list. Closing this one

**Pull request closed without merging**
