### PR TITLE
docs(contributors): update Contributors section considering latest releases

### PR DESCRIPTION
**Pull request by smoya**
This PR updates Contributors section, adding contributions for the contributors of latest few releases.

### CODE REVIEW

**Review by dalelane — APPROVED** [review]

**Review by derberg — APPROVED** [review]

**Review by fmvilas — APPROVED** [review]

**Review by fmvilas — APPROVED** [review]

**Comment by fmvilas** [comment]
I double approved so there's no doubt 😂

**Comment by derberg** [comment]
/rtm

@smoya thanks mate for taking care to keep the list up to date 🙏🏼

**Comment by fmvilas** [comment]
Forget about the last comment saying it was released in version 2.5.0-next-major-spec.1. I made a mistake and it created this version but it should actually be `3.0.0-next-major-spec.1`. There's a notice in the [release](https://github.com/asyncapi/spec/releases/tag/v2.5.0-next-major-spec.1). Apologies for the noise.

**Comment by derberg** [comment]
Recent comments about the release from the bot were added by mistake. More details in https://github.com/asyncapi/spec/issues/899

**Pull request merged**
