### PR TITLE
feat: simplify parameter object

### LINKED ISSUE #583: Inconsistencies for schemas in server.variables and channel.parameters
I'm wondering why schema (doc/constraints) for server variables uses only a subset of JSON Schema (enum, default, examples and description) rather a full set of JSON Schema keywords like `channel.parameters.[*].schema`. I can understand that if you have server's [url/host](https://github.com/asyncapi/spec/issues/547) then you should have in 99% cases "hardcoded" variables for it - variable's type can be only a string and with some set of values (`enum`), but maybe we should allow also more complex schema like `pattern` etc? If channel's parameter has it (which is more generic), so why not server variable? I need some clarification in this place. 

Another question/problem: if server variable can have defined `enum` then for what the `examples` exists? I mean if there is a case, when given variable have a predefined set of values (`enum`) then `examples` === `enum`, so `examples` is unnecessary. Other case, when `examples` field is used to describe possible "other" values for variable, so maybe then we should allow more complex schema to describe the variable (see my first question)?

I hope that you understand my concerns and thanks very much for comments!

### PR DESCRIPTION
**Pull request by fmvilas**
Following our conversations in the Spec 3.0 meetings, here's the simplification of the Parameter Object.

Fixes #583

### CODE REVIEW

**Review by dalelane — APPROVED** [review]
👍

**Comment by jonaslagoni** [comment]
@fmvilas is it true this require no changes to the parser nor spec-json-schema?

**Comment by fmvilas** [comment]
🤔 No, I think it does require changes in these repos. I just didn't do them. Easy change though.

**Comment by jonaslagoni** [comment]
Alright, added it to the progress section of https://github.com/asyncapi/spec/issues/691 to track it.

**Pull request merged**
