### PR TITLE
fix: unify Message and MessageTrait examples description

### PR DESCRIPTION
**Pull request by char0n**
Refs #604

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]
LGTM @derberg @fmvilas do you want to add something?

**Comment by derberg** [comment]
it touches the specification, bug fix imho and therefore `fix: ` that will have to trigger 2.1.1 release. We have the  same issue in json schema -> https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/2.1.0.json#L934 instead of https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/2.1.0.json#L699

**Comment by magicmatatjahu** [comment]
@derberg I think that it is editorial change, because we "missed" changing the description of the examples in the Message Trait Object, so `docs:` is enough for me - it other words, Message Trait Object inheritances the shape from Message Object, so we don't change it's shape, but only fix it.

I also agree that json-schemas should be updated.

**Comment by derberg** [comment]
> but only fix it

exactly, we fix it 😄 and fix is so significant that even json schema needs an update. This would be our first patch release so better to wait for @fmvilas opinion too. For now, it is 2.1.1 for me, pure bug fix in the specification, not simple editorial change.

@char0n is it ok for you to provide a fix in a JSON Schema too? Let us discuss there on PR but I guess to avoid "forgetting" things in the future, `examples` should be reused from `definitions`

**Comment by magicmatatjahu** [comment]
> but only fix it

I shouldn't write it 😆  For me it's editorial change.

**Comment by char0n** [comment]
@derberg yep I'll amend the metaschema as well

**Review by fmvilas — APPROVED** [review]

**Comment by char0n** [comment]
@derberg schema fixed in https://github.com/asyncapi/spec-json-schemas/pull/85

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Review by magicmatatjahu — APPROVED** [review]
LGTM

**Comment by derberg** [comment]
@fmvilas you need to share your opinion on PR title as for me it is `fix:` and for @magicmatatjahu  it is `docs:`

if we agree with `fix: ` we should rather push it to release branch and release in a week together with `2.2` release

**Comment by fmvilas** [comment]
It's indeed a fix. The previous meaning was different than the current meaning.

**Comment by derberg** [comment]
@char0n can you please change base branch to release branch for this one, the one that points to September release?

**Comment by char0n** [comment]
I've changed the base but I'd have to redo the PR so that unrelated commits are not visible here.

**Comment by derberg** [comment]
rebasing with release branch should do the trick, no?

**Comment by char0n** [comment]
PR force-pushed and rebased on top of 2021-09-release

**Pull request merged**
