### PR TITLE
docs: set proper indentation for the TOC

### PR DESCRIPTION
**Pull request by smoya**
The TOC has some wrong indentation. This PR fixes that.

Note: this doesn't affect website navigation bar.

### CODE REVIEW

**Review by dalelane — APPROVED** [review]

**Comment by derberg** [comment]
This is not going to fix website. TOC from original markdown file is removed when it is pushed to website repo -> https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml#L55

right-hand side nav/toc in the website is generated dynamically. Separate issue/PR is needed there

**Comment by smoya** [comment]
> This is not going to fix website. TOC from original markdown file is removed when it is pushed to website repo -> https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml#L55
> 
> right-hand side nav/toc in the website is generated dynamically. Separate issue/PR is needed there

That's actually what I needed to know. Thanks!

This PR is still valid for fixing the TOC in the spec document, even though it is a little detail. I'm changing the PR description to make it clear.

**Review by derberg — APPROVED** [review]
LGTM

**Comment by smoya** [comment]
FYI, issue created in website repo: https://github.com/asyncapi/website/issues/1030

**Review by fmvilas — APPROVED** [review]

**Pull request merged**
