### PR TITLE
ci: update release workflow

### LINKED ISSUE #938: update release workflow in release branch
Release https://github.com/asyncapi/spec/blob/next-major-spec/.github/workflows/release.yml needs update

Because of https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

```yml
      - name: Setup Node.js
        uses: actions/setup-node@v1
```

needs to be replaced with
```yml
- name: Setup Node.js
   uses: actions/setup-node@v3
   with:
      node-version: 18
```

also 
```
npm install conventional-changelog-conventionalcommits
```

update to
```
npm install --save-dev conventional-changelog-conventionalcommits@5.0.0
```

and switch:
```
actions/checkout@v2
```

to 
```
actions/checkout@v3
```

### PR DESCRIPTION
**Pull request by kaushik-rishi**
---
title: "Update release workflow"
---

---

**Related issue(s):**
Fixes #938 

---

### CODE REVIEW

**Comment by derberg** [comment]
@kaushik-rishi sorry for looking into it so late

`ci: update release workflow on release branch` - it is not correct. You are targeting `master`, not release branch.

- Just update the title to `ci: update release workflow` and we can merge this PR if it is already in place
- Please open another PR that modifies release workflow located in `next-major-spec` branch, and new PR `ci: update release workflow on release branch` should target `next-major-spec`

**Comment by kaushik-rishi** [comment]
Sure @derberg

**Comment by derberg** [comment]
@kaushik-rishi please have a look so we can merge the fix. Unfortunately current release workflow do not work

**Comment by kaushik-rishi** [comment]
Sure @derberg 
Taking a look.

**Review by derberg — APPROVED** [review]
LGTM

ping me when you have another PR ready, for `next-major-spec` branch

**Comment by smoya** [comment]
@all-contributors please add @kaushik-rishi  for maintenance,infra

**Pull request merged**
