### PR TITLE
feat: allow servers and channels to be defined as components

### PR DESCRIPTION
**Pull request by smoya**
> Note that this PR is targeting `asyncapi:2022-01-release` branch, so merging it won't release a new version.

**Description**
This PR is part of https://github.com/asyncapi/spec/issues/660.
It allows both `servers` and `channels` to be defined as (and referenced from) components, meaning the following will be now valid:

```yaml
servers:
  production:
    $ref: '#/components/servers/myserver'
channels:
  some/events:
    $ref: '#/components/channels/myChannel'
components:
  servers:
    myserver:
      url: "http://localhost:5000/ws"
      protocol: ws
  channels:
    myChannel:
      description: "mychannel"
```

**Related issue(s)**
https://github.com/asyncapi/spec/issues/660

### CODE REVIEW

**Comment by derberg** [comment]
@smoya fyi this pr goes to master, not release branch. Also, we release stuff from release branches, we create release candidates that are automatically published to the website. So you should have prefix `feat: ` as you are introducing a feature

FYI, I haven't looked into the proposal itself, just quickly noticed what you wrote when I saw a pop up in slack channel and thought I will give you a quick heads up. For proposals, I plan to delegate some time next week to jump into the review in spec repo

**Comment by smoya** [comment]
This branch is now up-to-date with `2022-01-release` and all conflicts have been solved. cc @derberg

**Review by derberg — APPROVED** [review]
/dnm

**Review by fmvilas — APPROVED** [review]

**Comment by derberg** [comment]
All stuff in place, reference implementation provided and will be released to release branches after this merge.

/rtm

**Pull request merged**
